# Copyright 2015 ARM Limited, All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
This module contains classes to represent Test Specification interface that defines the data to be generated by/from
a build system to give enough information to Greentea.
"""


class TestBinary:
    """
    Class representing a Test Binary.
    """
    def __init__(self, path, flash_method):
        """
        ctor.

        :return:
        """
        self.path = path
        # attributes
        self.flash_method = flash_method

    def get_path(self):
        """
        Gives binary path.
        :return:
        """
        return self.path


class Test:
    """
    class representing a Test artifact that may contain more than one test binaries.
    """
    def __init__(self, name):
        """
        ctor.

        :param name:
        :return:
        """
        self.name = name
        self.binaries = {}

    def get_name(self):
        """
        Gives test name.

        :return:
        """
        return self.name

    def get_binaries(self):
        """
        Gives test binaries.
        :return:
        """
        return self.binaries

    def get_binary(self, type):
        """
        Gives a test binary of specific flash type.

        :param type:
        :return:
        """
        return self.binaries[type]

    def parse(self, test_json):
        """
        Parse json contents into object.

        :param test_json:
        :return:
        """
        print test_json
        for _, binary in test_json['binaries'].iteritems():
            tb = TestBinary(binary['path'], binary['flash_method'])
            self.binaries[binary['flash_method']] = tb

    def add_binary(self, name, path, flash_method):
        """
        Add binary to the test.

        :param name:
        :param path:
        :param flash_method:
        :return:
        """
        self.binaries[name] = TestBinary(path, flash_method)


class TestBuild:
    """
    class for Test build.
    """

    def __init__(self, name, platform, toolchain, baud_rate, base_path):
        """
        ctor.

        :param platform:
        :param toolchain:
        :return:
        """
        self.name = name
        self.platform = platform
        self.toolchain = toolchain
        self.baud_rate = baud_rate
        self.base_path = base_path
        self.tests = {}

    def get_name(self):
        """
        Gives build name.

        :return:
        """
        return self.name

    def get_platform(self):
        """
        Gives mbed classic platform name.

        :return:
        """
        return self.platform

    def get_toolchain(self):
        """
        Gives toolchain

        :return:
        """
        return self.toolchain

    def get_baudrate(self):
        """
        Gives baud rate.

        :return:
        """
        return self.baud_rate

    def get_path(self):
        """
        Gives path.

        :return:
        """
        return self.base_path

    def get_tests(self):
        """
        Gives tests dict keyed by test name.

        :return:
        """
        return self.tests

    def parse(self, target_spec):
        """
        Parse Test build json.

        :param target_spec:
        :return:
        """
        import json
        print json.dumps(target_spec['tests'], indent=4)
        for name, test_json in target_spec['tests'].iteritems():
            test = Test(name)
            test.parse(test_json)
            self.tests[name] = test

    def add_test(self, name, test):
        """
        Add test.

        :param name:
        :param test:
        :return:
        """
        self.tests[name] = test


class TestSpec:
    """
    Test specification. Contains Builds.
    """
    def __init__(self):
        """
        ctor.

        :return:
        """
        self.target_test_spec = {}

    def parse(self, spec):
        """
        Parse test spec json.

        :param spec:
        :return:
        """
        for _, build in spec['builds'].iteritems():
            if 'name' in build:
                build_name = build['name']
            else:
                build_name = "%s-%s" % (build['platform'], build['toolchain'])
            tb= TestBuild(build_name, build['platform'], build['toolchain'], build['baud_rate'], build['base_path'])
            tb.parse(build)
            self.target_test_spec[build_name] = tb

    def get_test_builds(self):
        """
        Gives test builds.
        :return:
        """
        return self.target_test_spec.values()

    def get_test_build(self, build_name):
        """
        Gives test build with given name.

        :param build_name:
        :return:
        """
        return self.target_test_spec[build_name]

    def add_test_builds(self, name, test_build):
        """
        Add test build.

        :param name:
        :param test_build:
        :return:
        """
        self.target_test_spec[name] = test_build
